### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jkmg** [raghavagps/Pfeature#5]
Hello,

I get the following error when doing python setup.py install:

/opt/Python-3.7.7/Lib/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running install
running build
running build_py
error: can't copy 'Pfeature/': doesn't exist or not a regular file

any ideas?

**Comment by sayalaruano** [comment]
Hello @jkmg, I had the same error when I tried to install this library on my laptop. Did you figure out the solution for this error?

**Comment by vikassethi09** [comment]
I am getting the same error. Is there any video tutorials for this?

**Comment by sayalaruano** [comment]
Hey @vikassethi09, I did not find any videos or other resources to solve this problem. However, I realized that in my case the problem was because I was using Debian as the OS in my laptop. I verified this because I tried the same with a Docker image based on Debian and had the same issue. I solved this problem by working with a Docker image based on Ubuntu or also working in Colab, which usually have Ubuntu based severs. What is your OS ?

**Comment by vikassethi09** [comment]
I am using this on windows. Well noob to all this.

**Comment by Sau-bio-info** [comment]
@sayalaruano I am working on colab and facing same issue.

**Comment by GhsJahanmir** [comment]
@jkmg 

I added  a "."  to the third line of setup.py file  (packagedata={'Pfeature': ['./*']})   and it solved the installation issue. 
it may help you.
it works on google colab.
On windows, installation issues solved but in the "import Pfeature"  step, it can not find the CSV files.
